name: Build Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master, release*]

jobs:
  build-test:
    name: resolve-dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18.17.1]
    steps:
      - uses: actions/checkout@v3
      - name: Rebase # Rebase with master or release* (branch against which PR is raised)
        if: github.event_name == 'pull_request'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git rebase origin/${{ github.event.pull_request.base.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --prod --frozen-lockfile
      - run: yarn build
      - run: yarn build-mco
      - run: yarn build-client
      - run: yarn install # Install dev. deps.
      - run: yarn lint
      - run: yarn format-test
      - run: yarn i18n-test
      - run: yarn test-coverage
      - run: yarn analyze-odf
      - run: yarn analyze-mco
      - run: yarn analyze-client
